// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSg-fXMSUol7q3wuN4JD8ByvkhKHTBbIg',
    appId: '1:536142490213:web:040884905d48b9a4d2b48c',
    messagingSenderId: '536142490213',
    projectId: 'ecommerceapp-2e40e',
    authDomain: 'ecommerceapp-2e40e.firebaseapp.com',
    storageBucket: 'ecommerceapp-2e40e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAni5_goRGxNxG7XSSsBtO8L6osXTiwJoE',
    appId: '1:536142490213:android:020af30d6b8b691ad2b48c',
    messagingSenderId: '536142490213',
    projectId: 'ecommerceapp-2e40e',
    storageBucket: 'ecommerceapp-2e40e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmaligQo6DMXoYpPoKOW_oZrEJSCPlY60',
    appId: '1:536142490213:ios:f3e3afcd9313b3afd2b48c',
    messagingSenderId: '536142490213',
    projectId: 'ecommerceapp-2e40e',
    storageBucket: 'ecommerceapp-2e40e.appspot.com',
    androidClientId: '536142490213-80im0cr3jki1pntm03ranj5e9ib9s68p.apps.googleusercontent.com',
    iosClientId: '536142490213-a8u2p4o5599s42g41v1i01jff78ctplb.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmaligQo6DMXoYpPoKOW_oZrEJSCPlY60',
    appId: '1:536142490213:ios:f3e3afcd9313b3afd2b48c',
    messagingSenderId: '536142490213',
    projectId: 'ecommerceapp-2e40e',
    storageBucket: 'ecommerceapp-2e40e.appspot.com',
    androidClientId: '536142490213-80im0cr3jki1pntm03ranj5e9ib9s68p.apps.googleusercontent.com',
    iosClientId: '536142490213-a8u2p4o5599s42g41v1i01jff78ctplb.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSg-fXMSUol7q3wuN4JD8ByvkhKHTBbIg',
    appId: '1:536142490213:web:69e0c6f1b5d21da5d2b48c',
    messagingSenderId: '536142490213',
    projectId: 'ecommerceapp-2e40e',
    authDomain: 'ecommerceapp-2e40e.firebaseapp.com',
    storageBucket: 'ecommerceapp-2e40e.appspot.com',
  );
}
